# Dockerfile.backend

FROM node:20

WORKDIR /app

# Copy only package files first (better caching)
COPY backend/package*.json ./

RUN npm install

# Copy rest of backend code
COPY backend/ .

EXPOSE 8000

CMD ["node", "src/index.js"]