# Dockerfile.frontend

FROM node:20

WORKDIR /app

# Copy package files first
COPY frontend/package*.json ./

RUN npm install

# Copy rest of frontend code
COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]